version: '3'
services:
  postgres:
    image: postgres:latest
  hasura:
    image: hasura/graphql-engine
    ports:
      - "1337:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres_password@postgres:5432/postgres # postgresql defaults
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET="mysupersecretsecret"