version: '3.1'
services:
  postgres:
    build:
      context: ./database
  hasura:
    restart: always
    build:
      context: ./hasura
    ports:
      - "1337:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres_password@postgres:5432/postgres # postgresql defaults
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=jkasvbdhbjaasdkahbsd
  rabbitmq:
    build:
      context: ./message-broker
    ports:
      - "5672:5672"
  rabbitmq-admin:
    build:
      context: ./message-broker
      dockerfile: Dockerfile-rbmq-management
    ports:
      - "15672:15672"
